version: "3.8"
services:
  ktor-app:
    build: .
    ports:
      - 4551:4551
    
  ngrok:
    image: shkoliar/ngrok:latest
    ports:
      - 4552:4552
    links:
      - ktor-app
    environment:
      - DOMAIN=ktor-app
      - PORT=80
